kind: Service
apiVersion: v1
metadata:
  name: realyticsai-frontend-service
  labels:
    app: realyticsai-frontend
spec:
  type: LoadBalancer
  selector:
    app: realyticsai-frontend
  ports:
    -
      port: 80
      targetPort: 3000
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: realyticsai-frontend-deployment
  labels:
    app: realyticsai-frontend
spec:
  selector:
    matchLabels:
      app: realyticsai-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: realyticsai-frontend
        version: v1
    spec:
      containers:
        -
          name: realyticsai-frontend
          image: 'eu-frankfurt-1.ocir.io/oraseemeaceeociworkshop/ivandelic/realyticsai/realyticsai-frontend:latest'
          imagePullPolicy: Always
          ports:
            -
              containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: http://realyticsai-backend.micro.ivandelic.com
            - name: REACT_APP_OBP_RESTPROXY1_ADDRESS
              value: https://1DF8C89030BF4AE39AFD38679326BE69.blockchain.ocp.oraclecloud.com:443/restproxy1/bcsgw/rest/v1/transaction/invocation
            - name: REACT_APP_OBP_RESTPROXY1_USERNAME
              valueFrom:
                secretKeyRef:
                  name: obp-restproxy1
                  key: username
            - name: REACT_APP_OBP_RESTPROXY1_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: obp-restproxy1
                  key: password
      imagePullSecrets:
        -
          name: ocirsecret